baseURL: "https://liming.ml/"
title: 怠惰
paginate: 5
theme: PaperMod
defaultContentLanguage: zh

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: 怠惰
    description: "おまえ怠惰ですね"
    keywords: [Blog, Hugo, PaperMod]
    author: Ric
    # author: ["Me", "You"] # multiple authors
    images: ["https://pbs.twimg.com/profile_images/777912200048496640/69XpxZTW_400x400.jpg"]
    DateFormat: "2006-01-02"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments:
        enabled: true
        provider: waline
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/img/favicon.ico"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "主页"
        icon: /img/486.jpeg
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: 怠惰
        subtitle: "你很怠惰呢"
        imageUrl: "https://pbs.twimg.com/profile_images/777912200048496640/69XpxZTW_400x400.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: me
        buttons:
            - name: 文章
              url: posts
            - name: 标签
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "你好 \U0001F44B"
        Content: 欢迎来到我的博客

    socialIcons:
        - name: twitter
          url: "https://twitter.com/ricardomlee"
        # - name: stackoverflow
        #   url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/ricardomlee"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/ricardomlee/ric-hugo/blob/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: 分类
          url: /categories/
          weight: 10
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 20
        - identifier: about
          name: 关于
          url: /about/
          weight: 30
        - identifier: mirror
          name: 镜像
          url: https://ricli.ml
          weight: 40
        - identifier: nas
          name: NAS
          url: /nas/
          weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai